# The blog-renderer ClusterImageTemplate uses a Tekton Task to
# render a blog given URLs for the blog's and blog-gen's source code.
#
# NOTE: You don't _have_ to use Tekton here! The beauty of
# ClusterImageTemplates is that you can use whatever tool you need to get
# the job done (the "job", in this case, being an image containing our
# blog's assets).
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: blog-renderer
spec:
  healthRule:
    singleConditionType: Ready
  lifecycle: tekton
  imagePath: .status.pipelineResults[?(@.name=="image_path")].value
  ytt: |
    #@ load("@ytt:data", "data")
    ---
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: #@ data.values.workload.metadata.name + "-render-blog-run-"
    spec:
      params:
        - name: blog_gen_url
          value: #@ data.values.configs.blog-config.blog_gen_url
        - name: blog_gen_version
          value: #@ data.values.configs.blog-config.blog_gen_version
        - name: blog_url
          value: #@ data.values.configs.blog-config.blog_url
        - name: registry_name
          value: #@ data.values.configs.blog-config.blog_registry_name
      workspaces:
        - name: blog-storage
          emptyDir: {}
        - name: scratch-space
          emptyDir: {}
        - name: blog-env-secret
          secret:
            name: #@ data.values.configs.blog-config.blog_env_kubernetes_secret
        - name: blog-registry-secret
          secret:
            name: #@ data.values.configs.blog-config.blog_registry_secret
      pipelineRef:
        name: render-the-blog
