apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: blog.carlosnunez.me
  labels:
    is-blog: "true"
spec:
  # All we need to do here is provide the parameters required by our Supply Chain.
  #
  # NOTE: We're using `params` to specify the Git repository of the blog
  # that we want to deploy to demonstrate a minimal, simple example of a Supply Chain.
  #
  # A more advanced Supply Chain example can use a `ClusterSourceTemplate` combined
  # with a `git` parameter and FluxCD to monitor a Git repository for changes
  # and re-invoke an execution of the Supply Chain on new pushes.
  params:
    - name: blog_url
      value: https://github.com/carlosonunez/blog.carlosnunez.me
    - name: blog_env_secret
      value: blog-secret
    - name: blog_registry_name
      value: docker.io/carlosnunez
